#**Campus_recruitment classification:**

##**Library importing**

In [1]:
import pandas as pd
import numpy as np
import matplotlib as pyplot

##**Uploading the dataset**

In [2]:
data =pd. read_csv("/content/datasets_596958_1073629_Placement_Data_Full_Class.csv")

In [3]:
data

sl_no gender  ssc_p    ssc_b  ...  specialisation  mba_p      status    salary
0        1      M  67.00   Others  ...          Mkt&HR  58.80      Placed  270000.0
1        2      M  79.33  Central  ...         Mkt&Fin  66.28      Placed  200000.0
2        3      M  65.00  Central  ...         Mkt&Fin  57.80      Placed  250000.0
3        4      M  56.00  Central  ...          Mkt&HR  59.43  Not Placed       NaN
4        5      M  85.80  Central  ...         Mkt&Fin  55.50      Placed  425000.0
..     ...    ...    ...      ...  ...             ...    ...         ...       ...
210    211      M  80.60   Others  ...         Mkt&Fin  74.49      Placed  400000.0
211    212      M  58.00   Others  ...         Mkt&Fin  53.62      Placed  275000.0
212    213      M  67.00   Others  ...         Mkt&Fin  69.72      Placed  295000.0
213    214      F  74.00   Others  ...          Mkt&HR  60.23      Placed  204000.0
214    215      M  62.00  Central  ...          Mkt&HR  60.22  Not Placed       NaN

[215 rows x 15 columns]

In [4]:
data. info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   sl_no           215 non-null    int64  
 1   gender          215 non-null    object 
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object 
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object 
 6   hsc_s           215 non-null    object 
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    object 
 9   workex          215 non-null    object 
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object 
 12  mba_p           215 non-null    float64
 13  status          215 non-null    object 
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB


In [5]:
data. isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

###dropping salary ,sl_no ,ssc_b,hsc_b features

In [6]:
data. drop(['salary','sl_no','ssc_b','hsc_b'],axis=1,inplace=True)

In [7]:
data

gender  ssc_p  hsc_p     hsc_s  ...  etest_p specialisation  mba_p      status
0        M  67.00  91.00  Commerce  ...     55.0         Mkt&HR  58.80      Placed
1        M  79.33  78.33   Science  ...     86.5        Mkt&Fin  66.28      Placed
2        M  65.00  68.00      Arts  ...     75.0        Mkt&Fin  57.80      Placed
3        M  56.00  52.00   Science  ...     66.0         Mkt&HR  59.43  Not Placed
4        M  85.80  73.60  Commerce  ...     96.8        Mkt&Fin  55.50      Placed
..     ...    ...    ...       ...  ...      ...            ...    ...         ...
210      M  80.60  82.00  Commerce  ...     91.0        Mkt&Fin  74.49      Placed
211      M  58.00  60.00   Science  ...     74.0        Mkt&Fin  53.62      Placed
212      M  67.00  67.00  Commerce  ...     59.0        Mkt&Fin  69.72      Placed
213      F  74.00  66.00  Commerce  ...     70.0         Mkt&HR  60.23      Placed
214      M  62.00  58.00   Science  ...     89.0         Mkt&HR  60.22  Not Placed

[215 rows x 11 columns]

##**Seperating Features and Target**

In [8]:
X=data.iloc[:,:-1]
Y=data.iloc[:,-1].values

In [9]:
X

gender  ssc_p  hsc_p     hsc_s  ...  workex etest_p specialisation  mba_p
0        M  67.00  91.00  Commerce  ...      No    55.0         Mkt&HR  58.80
1        M  79.33  78.33   Science  ...     Yes    86.5        Mkt&Fin  66.28
2        M  65.00  68.00      Arts  ...      No    75.0        Mkt&Fin  57.80
3        M  56.00  52.00   Science  ...      No    66.0         Mkt&HR  59.43
4        M  85.80  73.60  Commerce  ...      No    96.8        Mkt&Fin  55.50
..     ...    ...    ...       ...  ...     ...     ...            ...    ...
210      M  80.60  82.00  Commerce  ...      No    91.0        Mkt&Fin  74.49
211      M  58.00  60.00   Science  ...      No    74.0        Mkt&Fin  53.62
212      M  67.00  67.00  Commerce  ...     Yes    59.0        Mkt&Fin  69.72
213      F  74.00  66.00  Commerce  ...      No    70.0         Mkt&HR  60.23
214      M  62.00  58.00   Science  ...      No    89.0         Mkt&HR  60.22

[215 rows x 10 columns]

###Converting to an array format

In [10]:
X=X.to_numpy()

In [11]:
X

array([['M', 67.0, 91.0, ..., 55.0, 'Mkt&HR', 58.8],
       ['M', 79.33, 78.33, ..., 86.5, 'Mkt&Fin', 66.28],
       ['M', 65.0, 68.0, ..., 75.0, 'Mkt&Fin', 57.8],
       ...,
       ['M', 67.0, 67.0, ..., 59.0, 'Mkt&Fin', 69.72],
       ['F', 74.0, 66.0, ..., 70.0, 'Mkt&HR', 60.23],
       ['M', 62.0, 58.0, ..., 89.0, 'Mkt&HR', 60.22]], dtype=object)

In [12]:
Y

array(['Placed', 'Placed', 'Placed', 'Not Placed', 'Placed', 'Not Placed',
       'Not Placed', 'Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Not Placed', 'Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Not Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Not Placed',
       'Placed', 'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Not Placed', 'Placed', 'Placed', 'Placed', 'Not Placed',
  

##**One Hot Encoder**

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

###Encoding categorical features

In [14]:
 ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,3,5,6,8])], remainder='passthrough')

In [15]:
 X=np.array(ct.fit_transform(X))

In [16]:
X

array([[0.0, 1.0, 0.0, ..., 58.0, 55.0, 58.8],
       [0.0, 1.0, 0.0, ..., 77.48, 86.5, 66.28],
       [0.0, 1.0, 1.0, ..., 64.0, 75.0, 57.8],
       ...,
       [0.0, 1.0, 0.0, ..., 73.0, 59.0, 69.72],
       [1.0, 0.0, 0.0, ..., 58.0, 70.0, 60.23],
       [0.0, 1.0, 0.0, ..., 53.0, 89.0, 60.22]], dtype=object)

In [17]:
 temp=pd.DataFrame(data=X)

In [18]:
temp

0  1  2  3  4  5  6  7  8  9 10 11     12     13     14    15     16
0    0  1  0  1  0  0  0  1  1  0  0  1     67     91     58    55   58.8
1    0  1  0  0  1  0  0  1  0  1  1  0  79.33  78.33  77.48  86.5  66.28
2    0  1  1  0  0  1  0  0  1  0  1  0     65     68     64    75   57.8
3    0  1  0  0  1  0  0  1  1  0  0  1     56     52     52    66  59.43
4    0  1  0  1  0  1  0  0  1  0  1  0   85.8   73.6   73.3  96.8   55.5
..  .. .. .. .. .. .. .. .. .. .. .. ..    ...    ...    ...   ...    ...
210  0  1  0  1  0  1  0  0  1  0  1  0   80.6     82   77.6    91  74.49
211  0  1  0  0  1  0  0  1  1  0  1  0     58     60     72    74  53.62
212  0  1  0  1  0  1  0  0  0  1  1  0     67     67     73    59  69.72
213  1  0  0  1  0  1  0  0  1  0  0  1     74     66     58    70  60.23
214  0  1  0  0  1  1  0  0  1  0  0  1     62     58     53    89  60.22

[215 rows x 17 columns]

##**Label Encoder**

In [19]:
data['status'].unique

<bound method Series.unique of 0          Placed
1          Placed
2          Placed
3      Not Placed
4          Placed
          ...    
210        Placed
211        Placed
212        Placed
213        Placed
214    Not Placed
Name: status, Length: 215, dtype: object>

In [20]:
from sklearn.preprocessing import LabelEncoder

###Encoding target feature

In [21]:
le = LabelEncoder()

In [22]:
Y= le.fit_transform(Y)

In [23]:
Y

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

##**Splitting to train and Test data**

In [24]:
 from sklearn.model_selection import train_test_split

In [25]:
 X_train,X_test,Y_train,Y_test=train_test_split(X, Y, test_size=0.2)

In [26]:
X_train

array([[1.0, 0.0, 0.0, ..., 72.23, 55.53, 68.81],
       [0.0, 1.0, 0.0, ..., 60.0, 63.0, 52.38],
       [0.0, 1.0, 0.0, ..., 65.0, 86.0, 56.09],
       ...,
       [0.0, 1.0, 0.0, ..., 60.0, 84.0, 64.15],
       [0.0, 1.0, 0.0, ..., 72.0, 74.0, 53.62],
       [0.0, 1.0, 0.0, ..., 72.0, 84.0, 58.95]], dtype=object)

In [27]:
Y_train

array([1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1])

##**Standardisation of data**

In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
scaler = StandardScaler()

In [30]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [31]:
X_train

array([[ 1.31535498, -1.31535498, -0.20597146, ...,  0.79566888,
        -1.28061634,  1.15303029],
       [-0.76025104,  0.76025104, -0.20597146, ..., -0.84349831,
        -0.7231849 , -1.68939783],
       [-0.76025104,  0.76025104, -0.20597146, ..., -0.17335637,
         0.99313679, -1.04755922],
       ...,
       [-0.76025104,  0.76025104, -0.20597146, ..., -0.84349831,
         0.84389143,  0.34683948],
       [-0.76025104,  0.76025104, -0.20597146, ...,  0.76484235,
         0.0976646 , -1.47487495],
       [-0.76025104,  0.76025104, -0.20597146, ...,  0.76484235,
         0.84389143, -0.55277259]])

In [32]:
X_test

array([[-7.60251045e-01,  7.60251045e-01, -2.05971460e-01,
         9.43456353e-01, -8.68966076e-01,  7.04025691e-01,
        -2.34978135e-01, -6.22171017e-01,  7.50757194e-01,
        -7.50757194e-01,  9.21662826e-01, -9.21662826e-01,
        -1.46954205e+00, -2.03971987e+00, -1.24558347e+00,
        -6.48562219e-01, -1.85028998e+00],
       [-7.60251045e-01,  7.60251045e-01, -2.05971460e-01,
         9.43456353e-01, -8.68966076e-01,  7.04025691e-01,
        -2.34978135e-01, -6.22171017e-01,  7.50757194e-01,
        -7.50757194e-01,  9.21662826e-01, -9.21662826e-01,
        -4.68849736e-01,  5.42679140e-01, -1.73356369e-01,
        -4.24694172e-01, -9.78358293e-01],
       [ 1.31535498e+00, -1.31535498e+00, -2.05971460e-01,
        -1.05993245e+00,  1.15079291e+00, -1.42040271e+00,
        -2.34978135e-01,  1.60727513e+00,  7.50757194e-01,
        -7.50757194e-01, -1.08499548e+00,  1.08499548e+00,
         1.67954463e-01, -3.79606220e-01, -3.93279811e-02,
         1.72287287e-01,  1.0

##**Train on different algorithms**

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [34]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel= 'rbf')

In [35]:
l_cla.fit(X_train, Y_train)
k_cla.fit(X_train, Y_train)
d_cla.fit(X_train, Y_train)
r_cla.fit(X_train, Y_train)
s_cla.fit(X_train, Y_train)
ks_cla.fit(X_train, Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [36]:
l_pred = l_cla.predict(X_test)
k_pred = k_cla.predict(X_test)
d_pred = d_cla.predict(X_test)
r_pred = r_cla.predict(X_test)
s_pred = s_cla.predict(X_test)
ks_pred = ks_cla.predict(X_test)

###making confusion matrix

In [37]:
 from sklearn.metrics import confusion_matrix

In [38]:
l_c = confusion_matrix(Y_test, l_pred)
k_c = confusion_matrix(Y_test, k_pred)
d_c = confusion_matrix(Y_test, d_pred)
r_c = confusion_matrix(Y_test, r_pred)
s_c = confusion_matrix(Y_test, s_pred)
ks_c = confusion_matrix(Y_test, ks_pred)

In [39]:
 l_c

array([[ 8,  5],
       [ 0, 30]])

In [40]:
 k_c

array([[ 5,  8],
       [ 3, 27]])

In [41]:
d_c

array([[ 8,  5],
       [ 2, 28]])

In [42]:
r_c

array([[ 9,  4],
       [ 0, 30]])

In [43]:
s_c

array([[10,  3],
       [ 0, 30]])

In [44]:
ks_c

array([[ 7,  6],
       [ 0, 30]])

##**Results**

In [45]:
 from sklearn.metrics import accuracy_score

In [46]:
l_a = accuracy_score(Y_test, l_pred)
k_a = accuracy_score(Y_test, k_pred)
d_a = accuracy_score(Y_test, d_pred)
r_a = accuracy_score(Y_test, r_pred)
s_a = accuracy_score(Y_test, s_pred)
ks_a = accuracy_score(Y_test, ks_pred)

In [47]:
 print('Logistic Regression: ' + str(l_a) + '\nKNN: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(l_a))

Logistic Regression: 0.8837209302325582
KNN: 0.7441860465116279
Decision Tree: 0.8372093023255814
Random Forest: 0.9069767441860465
Linear SVC: 0.9302325581395349
Kernel SVC: 0.8837209302325582


##**Conclusion**

Linear SVC is giving higher accuracy as compared to all other algorithm, hence we can say that Linear SVC is giving best result for this dataset