#**REDWINE QUALITY**

#**REGRESSION**

##*Importing libraries*

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

##*Loading Dataset*

In [ ]:
data=pd.read_csv("/content/datasets_4458_8204_winequality-red.csv")

In [ ]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [ ]:
data. describe()

fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

In [ ]:
data. info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


##*Seperate Features and Target*

* Target is quality and rest columns as features

In [ ]:
X = data.iloc[: , :-1].values
Y = data.iloc[: , -1].values

In [ ]:
X

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [ ]:
Y

array([5, 5, 5, ..., 6, 5, 6])

##*Split to Train and Test Data*

In [ ]:
 from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)

In [ ]:
X_train

array([[1.04e+01, 4.10e-01, 5.50e-01, ..., 3.15e+00, 8.90e-01, 9.90e+00],
       [7.50e+00, 7.25e-01, 4.00e-02, ..., 3.26e+00, 5.30e-01, 9.60e+00],
       [1.09e+01, 5.30e-01, 4.90e-01, ..., 3.07e+00, 5.60e-01, 1.17e+01],
       ...,
       [1.02e+01, 6.45e-01, 3.60e-01, ..., 3.17e+00, 4.20e-01, 1.00e+01],
       [1.06e+01, 3.10e-01, 4.90e-01, ..., 3.26e+00, 8.60e-01, 1.07e+01],
       [7.90e+00, 7.20e-01, 1.00e-02, ..., 3.39e+00, 5.40e-01, 9.60e+00]])

In [ ]:
Y_train

array([6, 5, 6, ..., 6, 6, 5])

##*Standardising Data*

In [ ]:
 from sklearn.preprocessing import StandardScaler

 *feature scaling*

In [ ]:
sc = StandardScaler()

In [ ]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[ 1.19442858, -0.65146222,  1.42220822, ..., -1.03128243,
         1.3700716 , -0.47593816],
       [-0.47711347,  1.1030373 , -1.19558116, ..., -0.32678558,
        -0.75466996, -0.75869339],
       [ 1.48262549,  0.01691855,  1.114233  , ..., -1.54364376,
        -0.57760816,  1.22059327],
       ...,
       [ 1.07914982,  0.65745012,  0.44695335, ..., -0.90319209,
        -1.40389654, -0.38168641],
       [ 1.30970735, -1.20844619,  1.114233  , ..., -0.32678558,
         1.19300981,  0.27807581],
       [-0.24655595,  1.0751881 , -1.34956877, ...,  0.50580159,
        -0.69564936, -0.75869339]])

In [ ]:
X_test

array([[-0.0736378 , -1.37554138,  1.67885423, ...,  0.50580159,
         0.13063903,  0.18382407],
       [-1.28406481, -0.81855741, -0.63095992, ...,  0.69793709,
        -0.51858756, -0.94719688],
       [-0.01599842, -1.041351  ,  0.65227017, ...,  0.18557575,
         1.19300981,  0.56083105],
       ...,
       [-0.18891656, -1.37554138,  0.85758698, ...,  0.31366609,
         0.01259783,  0.74933454],
       [-0.24655595, -1.93252535,  0.65227017, ...,  0.12153059,
         1.606154  ,  0.84358629],
       [ 0.09928034,  0.74099772, -0.3743139 , ..., -1.15937276,
        -1.04977295, -1.13570038]])

##*Train on Different Algorithms*

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

In [ ]:
m_reg = LinearRegression()
p_reg = LinearRegression()
d_reg = DecisionTreeRegressor()
r_reg = RandomForestRegressor(n_estimators=500)
s_reg =SVR()

In [ ]:
X_poly = PolynomialFeatures(degree =2)
X_poly = X_poly.fit_transform(X_train)

In [ ]:
m_reg.fit(X_train, Y_train)
p_reg.fit(X_poly,Y_train)
d_reg.fit(X_train, Y_train)
r_reg.fit(X_train, Y_train)
s_reg.fit(X_train, Y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
temp = PolynomialFeatures(degree =2)
temp = temp.fit_transform(X_test)

In [ ]:
m_pred = m_reg.predict(X_test)
p_pred = p_reg.predict(temp)
d_pred = d_reg.predict(X_test)
r_pred = r_reg.predict(X_test)
s_pred = s_reg.predict(X_test)

##*Accuracy score of the algorithms*

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
m = r2_score(Y_test, m_pred)
p = r2_score(Y_test, p_pred)
d = r2_score(Y_test, d_pred)
r = r2_score(Y_test, r_pred)
s = r2_score(Y_test, s_pred)

In [ ]:
print('Logistic Regression: ' + str(m) + '\npolyfeatures: ' + str(p) + '\nDecision Tree: ' + str(d) + '\nRandom Forest: ' + str(r) + '\nSVR: ' + str(s))

Logistic Regression: 0.35296446219223343
polyfeatures: 0.372032047029044
Decision Tree: 0.04174573055028452
Random Forest: 0.5171416318785579
SVR: 0.38358867114893025


* From regression,random forest algorithm is having high accuracy

#**CLASSIFICATION**

In [ ]:
 dataset=pd.read_csv("/content/datasets_4458_8204_winequality-red.csv")

In [ ]:
dataset

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [ ]:
 dataset['quality'].unique()

array([5, 6, 7, 4, 8, 3])

##*Seperate Features  and Target*

In [ ]:
X = dataset.iloc[: , 1:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
X

array([[ 0.7  ,  0.   ,  1.9  , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 0.88 ,  0.   ,  2.6  , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 0.76 ,  0.04 ,  2.3  , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 0.51 ,  0.13 ,  2.3  , ...,  3.42 ,  0.75 , 11.   ],
       [ 0.645,  0.12 ,  2.   , ...,  3.57 ,  0.71 , 10.2  ],
       [ 0.31 ,  0.47 ,  3.6  , ...,  3.39 ,  0.66 , 11.   ]])

In [ ]:
Y

array([5, 5, 5, ..., 6, 5, 6])

##*Split to train and test data*

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X ,Y, test_size=0.20)

In [ ]:
 X_train, X_test, Y_train, Y_test = train_test_split(X ,Y, test_size=0.20)

In [ ]:
X_train

array([[ 0.54 ,  0.04 ,  3.   , ...,  3.69 ,  0.91 ,  9.4  ],
       [ 0.835,  0.   ,  2.   , ...,  3.39 ,  0.52 , 10.   ],
       [ 0.635,  0.1  ,  2.1  , ...,  3.29 ,  0.75 , 10.9  ],
       ...,
       [ 0.53 ,  0.06 ,  2.   , ...,  3.38 ,  0.83 , 10.3  ],
       [ 1.58 ,  0.   ,  2.1  , ...,  3.5  ,  0.4  , 10.9  ],
       [ 0.965,  0.   ,  2.2  , ...,  3.58 ,  0.67 , 10.2  ]])

In [ ]:
Y_train

array([6, 5, 6, ..., 6, 3, 5])

##*Standardising Data*

In [ ]:
 from sklearn.preprocessing import StandardScaler

*Feature Scaling*

In [ ]:
sc = StandardScaler()

In [ ]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[ 0.07188738, -1.20127195,  0.32484722, ...,  2.45595697,
         1.48927858, -0.96650913],
       [ 1.71922822, -1.40583565, -0.38519225, ...,  0.52249365,
        -0.82278817, -0.40290085],
       [ 0.60238697, -0.8944264 , -0.3141883 , ..., -0.12199413,
         0.54073837,  0.44251157],
       ...,
       [ 0.01604532, -1.0989901 , -0.38519225, ...,  0.45804487,
         1.01500848, -0.12109671],
       [ 5.87946187, -1.40583565, -0.3141883 , ...,  1.2314302 ,
        -1.53419333,  0.44251157],
       [ 2.44517503, -1.40583565, -0.24318435, ...,  1.74702042,
         0.06646827, -0.21503142]])

In [ ]:
X_test

array([[-1.04495387, -1.40583565, -0.52720014, ...,  2.39150819,
         0.77787342,  3.35448769],
       [-0.6261384 ,  0.43523767, -0.38519225, ...,  1.10253264,
        -0.11138302, -1.15437855],
       [ 2.75230637, -1.3035538 ,  0.60886301, ...,  1.10253264,
        -1.00063946,  0.53644629],
       ...,
       [-0.31900706,  1.1000697 ,  1.24789853, ..., -0.05754535,
         0.12575203,  2.13333642],
       [ 1.04912347, -0.8944264 ,  0.04083143, ...,  1.68257164,
        -0.9413557 ,  1.38185871],
       [ 0.46278181, -0.99670825, -0.3141883 , ...,  1.61812286,
         0.6593059 ,  0.630381  ]])

##*Train on different algorithm*

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [ ]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel= 'rbf')

In [ ]:
l_cla.fit(X_train, Y_train)
k_cla.fit(X_train, Y_train)
d_cla.fit(X_train, Y_train)
r_cla.fit(X_train, Y_train)
s_cla.fit(X_train, Y_train)
ks_cla.fit(X_train, Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
l_pred = l_cla.predict(X_test)
k_pred = k_cla.predict(X_test)
d_pred = d_cla.predict(X_test)
r_pred = r_cla.predict(X_test)
s_pred = s_cla.predict(X_test)
ks_pred = ks_cla.predict(X_test)

###*Making confusion matrix*

In [ ]:
 from sklearn.metrics import confusion_matrix

In [ ]:
l_c = confusion_matrix(Y_test, l_pred)
k_c = confusion_matrix(Y_test, k_pred)
d_c = confusion_matrix(Y_test, d_pred)
r_c = confusion_matrix(Y_test, r_pred)
s_c = confusion_matrix(Y_test, s_pred)
ks_c = confusion_matrix(Y_test, ks_pred)

In [ ]:
l_c

array([[  0,   0,   1,   0,   0,   0],
       [  0,   1,   8,   2,   0,   0],
       [  0,   1, 107,  30,   0,   0],
       [  0,   0,  46,  73,  11,   0],
       [  0,   0,   4,  15,  18,   0],
       [  0,   0,   0,   2,   1,   0]])

In [ ]:
k_c

array([[ 0,  0,  1,  0,  0,  0],
       [ 0,  1,  6,  4,  0,  0],
       [ 1,  2, 97, 35,  3,  0],
       [ 0,  1, 43, 78,  8,  0],
       [ 0,  0,  8, 11, 18,  0],
       [ 0,  0,  0,  2,  1,  0]])

In [ ]:
d_c

array([[  0,   0,   1,   0,   0,   0],
       [  0,   1,   7,   3,   0,   0],
       [  2,   3, 103,  24,   5,   1],
       [  1,   6,  30,  84,   8,   1],
       [  0,   1,   4,   5,  26,   1],
       [  0,   0,   0,   0,   2,   1]])

In [ ]:
r_c

array([[  0,   0,   1,   0,   0,   0],
       [  0,   1,   8,   2,   0,   0],
       [  0,   0, 112,  25,   1,   0],
       [  0,   0,  27,  97,   6,   0],
       [  0,   0,   5,   9,  23,   0],
       [  0,   0,   0,   1,   1,   1]])

In [ ]:
s_c

array([[  0,   0,   1,   0,   0,   0],
       [  0,   0,   9,   2,   0,   0],
       [  0,   0, 110,  28,   0,   0],
       [  0,   0,  46,  84,   0,   0],
       [  0,   0,   4,  33,   0,   0],
       [  0,   0,   0,   3,   0,   0]])

In [ ]:
ks_c

array([[  0,   0,   1,   0,   0,   0],
       [  0,   0,   9,   2,   0,   0],
       [  0,   0, 109,  29,   0,   0],
       [  0,   0,  41,  86,   3,   0],
       [  0,   0,   6,  16,  15,   0],
       [  0,   0,   0,   3,   0,   0]])

##*Accuracy score of the algorithms*

In [ ]:
 from sklearn.metrics import accuracy_score

In [ ]:
l_a = accuracy_score(Y_test, l_pred)
k_a = accuracy_score(Y_test, k_pred)
d_a = accuracy_score(Y_test, d_pred)
r_a = accuracy_score(Y_test, r_pred)
s_a = accuracy_score(Y_test, s_pred)
ks_a = accuracy_score(Y_test, ks_pred)

In [ ]:
print('Logistic regression : ' + str(l_a) + '\nKNN: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(l_a))

Logistic regression : 0.621875
KNN: 0.60625
Decision Tree: 0.671875
Random Forest: 0.73125
Linear SVC: 0.60625
Kernel SVC: 0.621875


 * From classification, random forest algorithm is having high accuracy

In [ ]:
check=[(dataset['quality']>6.5),(dataset['quality']<=6.5)]
display =['Good','Bad']
dataset['result']=np.select(check,display)

In [ ]:
dataset['result'].unique()

array(['Bad', 'Good'], dtype=object)

In [ ]:
dataset.iloc[1:10,:]

fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  result
1            7.8              0.88         0.00  ...      9.8        5     Bad
2            7.8              0.76         0.04  ...      9.8        5     Bad
3           11.2              0.28         0.56  ...      9.8        6     Bad
4            7.4              0.70         0.00  ...      9.4        5     Bad
5            7.4              0.66         0.00  ...      9.4        5     Bad
6            7.9              0.60         0.06  ...      9.4        5     Bad
7            7.3              0.65         0.00  ...     10.0        7    Good
8            7.8              0.58         0.02  ...      9.5        7    Good
9            7.5              0.50         0.36  ...     10.5        5     Bad

[9 rows x 13 columns]

#  **Conclusion**

 * Using both regression and classification,we can say that random forest to be the best algorithm for this dataset